export interface ICommonConfig {
    NODE_ENV: string;
    ORGANIZATION: string;

    REDIS_HOST: string;
    REDIS_PORT: number;
    REDIS_TTL: number;
    REDIS_PASSWORD: string;
    REDIS_USERNAME: string;
    IS_CACHE_ENABLE: boolean;

    RABBIT_MQ_HOST: string;
    RABBIT_MQ_PORT: number;
    RABBIT_MQ_URL: string;

    STAGE_PATH: string;
    IMAGE_SIZE_PIXEL: number;
    IMAGE_QUALITY: number;

    S3_BUCKET_NAME: string;
    AWS_ACCESS_KEY: string;
    AWS_SECRET_KEY: string;
    AWS_REGION: string;
    S3_IMAGE_PATH: string;

    GPT4V_KEY: string;
    GPT4V_ENDPOINT: string;

    SMTP_HOST: string;
    SMTP_PORT: number;
    SMTP_USERNAME: string;
    SMTP_PASSWORD: string;

    MAIL_ADMINISTRATOR: string;
    CLIENT_URL: string;

    POSTMARK_API: string;
    POSTMARK_SERVER_TOKEN: string;
    DEFAULT_MESSAGE_STREAM: string;
    DEFAULT_SIGNATURE_EMAIL: string;

    LESSON_S3_FOLDER: string;
    CHAT_S3_FOLDER: string;

    DEFAULT_LESSON_FILE_FORMAT: string;

    VECTOR_DB_ENDPOINT: string;
    VECTOR_DB_API_KEY: string;
    VECTOR_DB_API_VERSION: string;
    CHUNK_SIZE: number;
    CHUNK_OVERLAP: number;
    MAX_FILE_UPLOAD_LIMIT: number;
    GOOGLE_WEB_SEARCH_ENDPOINT: string;
    GOOGLE_WEB_SEARCH_API_KEY: string;
}

export enum ECommonConfig {
    NODE_ENV = 'NODE_ENV',
    ORGANIZATION = 'ORGANIZATION',

    REDIS_HOST = 'REDIS_HOST',
    REDIS_PORT = 'REDIS_PORT',
    REDIS_TTL = 'REDIS_TTL',
    REDIS_PASSWORD = 'REDIS_PASSWORD',
    REDIS_USERNAME = 'REDIS_USERNAME',
    IS_CACHE_ENABLE = 'IS_CACHE_ENABLE',

    RABBIT_MQ_HOST = 'RABBIT_MQ_HOST',
    RABBIT_MQ_PORT = 'RABBIT_MQ_PORT',
    RABBIT_MQ_URL = 'RABBIT_MQ_URL',

    STAGE_PATH = 'STAGE_PATH',
    IMAGE_SIZE_PIXEL = 'IMAGE_SIZE_PIXEL',
    IMAGE_QUALITY = 'IMAGE_QUALITY',

    S3_BUCKET_NAME = 'S3_BUCKET_NAME',
    AWS_ACCESS_KEY = 'AWS_ACCESS_KEY',
    AWS_SECRET_KEY = 'AWS_SECRET_KEY',
    AWS_REGION = 'AWS_REGION',
    S3_IMAGE_PATH = 'S3_IMAGE_PATH',

    GPT4V_KEY = 'GPT4V_KEY',
    GPT4V_ENDPOINT = 'GPT4V_ENDPOINT',

    SMTP_HOST = 'SMTP_HOST',
    SMTP_PORT = 'SMTP_PORT',
    SMTP_USERNAME = 'SMTP_USERNAME',
    SMTP_PASSWORD = 'SMTP_PASSWORD',

    MAIL_ADMINISTRATOR = 'MAIL_ADMINISTRATOR',
    CLIENT_URL = 'CLIENT_URL',

    POSTMARK_API = 'POSTMARK_API',
    POSTMARK_SERVER_TOKEN = 'POSTMARK_SERVER_TOKEN',
    DEFAULT_MESSAGE_STREAM = 'DEFAULT_MESSAGE_STREAM',
    DEFAULT_SIGNATURE_EMAIL = 'DEFAULT_SIGNATURE_EMAIL',

    LESSON_S3_FOLDER = 'LESSON_S3_FOLDER',
    CHAT_S3_FOLDER = 'CHAT_S3_FOLDER',

    DEFAULT_LESSON_FILE_FORMAT = 'DEFAULT_LESSON_FILE_FORMAT',

    VECTOR_DB_ENDPOINT = 'VECTOR_DB_ENDPOINT',
    VECTOR_DB_API_KEY = 'VECTOR_DB_API_KEY',
    VECTOR_DB_API_VERSION = 'VECTOR_DB_API_VERSION',
    CHUNK_SIZE = 'CHUNK_SIZE',
    CHUNK_OVERLAP = 'CHUNK_OVERLAP',
    MAX_FILE_UPLOAD_LIMIT = 'MAX_FILE_UPLOAD_LIMIT',
    GOOGLE_WEB_SEARCH_ENDPOINT = 'GOOGLE_WEB_SEARCH_ENDPOINT',
    GOOGLE_WEB_SEARCH_API_KEY = 'GOOGLE_WEB_SEARCH_API_KEY',
}
