apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
      - name: quiz-service
        image: your-docker-repo/quiz-service:latest
        ports:
        - containerPort: 3003
        env:
          - name: NODE_ENV
            value: "production"
