global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nestjs-service-api'
    scrape_interval: 15s
    metrics_path: /api/v1/metrics
    scrape_timeout: 10s
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'nestjs-service-assignment'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    static_configs:
      - targets: ['host.docker.internal:8181']
  - job_name: 'nestjs-service-quiz'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    static_configs:
      - targets: ['host.docker.internal:8182']
  - job_name: 'nestjs-service-background-job'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    static_configs:
      - targets: ['host.docker.internal:8183']
  - job_name: 'nestjs-service-chat'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    static_configs:
      - targets: ['host.docker.internal:8184']