apiVersion: apps/v1
kind: Deployment
metadata:
  name: leaderboard-service
  namespace: quiz-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: leaderboard-service
  template:
    metadata:
      labels:
        app: leaderboard-service
    spec:
      containers:
        - name: leaderboard-service
          image: your-docker-registry/leaderboard-service:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: leaderboard-service
  namespace: quiz-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: leaderboard-service
