export enum ERabbitMQueue {
    API_APP_QUEUE = 'API_APP_QUEUE',
    ASSIGNMENT_APP_QUEUE = 'ASSIGNMENT_APP_QUEUE',
    QUIZ_QUEUE = 'QUIZ_QUEUE',
    GAME_QUEUE = 'GAME_QUEUE',
    BACKGROUND_JOB_QUEUE = 'BACKGROUND_JOB_QUEUE',
    NOTIFICATION_QUEUE = 'NOTIFICATION_QUEUE',
    CHAT_QUEUE = 'CHAT_QUEUE',
}

export enum EBullQueue {
    EXTRACT_ISSUE_QUEUE = 'EXTRACT_ISSUE_QUEUE',
    MAIL_QUEUE = 'MAIL_QUEUE',
    EXTRACT_ISSUE_FAILED_QUEUE = 'EXTRACT_ISSUE_FAILED_QUEUE',
    MAIL_FAILED_QUEUE = 'MAIL_FAILED_QUEUE',
    GENERATE_LESSON_QUEUE = 'GENERATE_LESSON_QUEUE',
    GENERATE_QUIZ_QUEUE = 'GENERATE_QUIZ_QUEUE',
    GENERATE_QUIZ_FAILED_QUEUE = 'GENERATE_QUIZ_FAILED_QUEUE',
    GENERATE_LESSON_FAILED_QUEUE = 'GENERATE_LESSON_FAILED_QUEUE',
}

export enum EBullQueueMessage {
    EXTRACT_MANY_ISSUES_MESSAGE = 'EXTRACT_MANY_ISSUES',
    EXTRACT_COMMON_ISSUE_MESSAGE = 'EXTRACT_COMMON_ISSUE',
    SEND_ACTIVATION_MAIL = 'SEND_ACTIVATION_MAIL',
    GENERATE_LESSON = 'GENERATE_LESSON',
    GENERATE_QUIZ = 'GENERATE_QUIZ',
}
