apiVersion: apps/v1
kind: Deployment
metadata:
  name: question-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: question-service
  template:
    metadata:
      labels:
        app: question-service
    spec:
      containers:
      - name: question-service
        image: your-docker-repo/question-service:latest
        ports:
        - containerPort: 3004
        env:
          - name: NODE_ENV
            value: "production"
